In [18]:
from sklearn.impute import SimpleImputer
from sklearn.datasets import load_breast_cancer
import numpy as np

#Data
BreastData = load_breast_cancer()
X = BreastData.data
y = BreastData.target

#Data Cleaning
ImputedModule = SimpleImputer(missing_values=np.nan, strategy = 'mean')
ImputedX = ImputedModule.fit(X)
X = ImputedX.transform(X)

print(x[:10])
print(y[:10])

[[-0.41771302  0.19615885  1.0897216 ]
 [-0.34340947  0.16126576  0.89587993]
 [ 0.56664517 -0.26609768 -1.47825288]
 [-0.30444983  0.14297023  0.79424279]
 [-0.65456851  0.30738665  1.70762559]
 [ 0.32699955 -0.15355963 -0.85307006]
 [-0.36123124  0.1696349   0.94237303]
 [-0.46166624  0.21679937  1.20438591]
 [ 0.38170749 -0.17925058 -0.99579108]
 [-0.27022913  0.12690013  0.7049685 ]]
[0 0 0 0 0 0 0 0 0 0]


In [21]:
from sklearn.impute import SimpleImputer
import numpy as np


data = [[1,2,np.nan],
        [3,np.nan,1],
        [5,np.nan,0],
        [np.nan,4,6 ],
        [5,0,np.nan],
        [4,5,5]]
#missing_values ex: 0, nan, ...
#you can use moean or median
imp = SimpleImputer(missing_values=np.nan,
                    strategy='mean')
imp.fit(data)

modified_data = imp.transform(data)
print(modified_data)


[[1.   2.   3.  ]
 [3.   2.75 1.  ]
 [5.   2.75 0.  ]
 [3.6  4.   6.  ]
 [5.   0.   3.  ]
 [4.   5.   5.  ]]


In [23]:
from sklearn.impute import SimpleImputer
import numpy as np


data = [[1,2,0],
        [3,0,1],
        [5,0,0],
        [0,4,6],
        [5,0,0],
        [4,5,5]]

imp = SimpleImputer(missing_values=0,
                    strategy='mean')
imp.fit(data)

modified_data = imp.transform(data)
print(modified_data)


[[1.         2.         4.        ]
 [3.         3.66666667 1.        ]
 [5.         3.66666667 4.        ]
 [3.6        4.         6.        ]
 [5.         3.66666667 4.        ]
 [4.         5.         5.        ]]
